version: "3.9"
services:
  key-extractor:
    image: key-extractor:latest
    ports:
      - "1234:1234"
    restart: always
    depends_on:
      - summarizer

  summarizer:
    image: summarizer:latest
    ports:
      - "1235:1235"
    restart: always
    depends_on:
      - question-generator

  question-generator:
    image: question-generator:latest
    ports:
      - "1236:1236"
    restart: always